version: "3.8"
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    # No ports exposed to host - only accessible via proxy
    expose:
      - "8080"
    volumes:
      - $PWD/tessdata:/usr/share/tessdata:rw
      - $PWD/config:/configs:rw
      # - $PWD/logs:/logs:rw
    environment:
      SECURITY_ENABLELOGIN: "false"
      LANGS: "de_DE,en_US"
      SYSTEM_DEFAULTLOCALE: de-DE
      UI_APPNAME: Stirling-PDF
      UI_HOMEDESCRIPTION: Demo site for Stirling-PDF Latest
      UI_APPNAMENAVBAR: Stirling-PDF Latest
      SYSTEM_MAXFILESIZE: "500"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "false"
      SHOW_SURVEY: "false"
      # Subpath configuration
      SERVER_SERVLET_CONTEXTPATH: /pdf
      SERVER_SERVLET_SESSION_COOKIE_PATH: /pdf
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/pdf/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/pdf/ | grep -qv 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    restart: on-failure:5
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: docker-proxy_proxy
