networks:
  docker-proxy_proxy:
    external: true
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    networks:
      - docker-proxy_proxy
    volumes:
      - $PWD/tessdata:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - $PWD/extraConfigs:/configs
    # - /location/of/customFiles:/customFiles/
    # - /location/of/logs:/logs/
    environment:
      DOCKER_ENABLE_SECURITY: false
      SYSTEM_ROOTURIPATH: /pdf
