version: '3.8'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - $PWD/tessdata:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - $PWD/extraConfigs:/configs
#      - /location/of/customFiles:/customFiles/
#      - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
